import { createPagesFunctionHandler } from '@react-router/cloudflare';
import type { ServerBuild } from 'react-router';

// Server build is generated by `npm run build` into build/server/index.js.
// The file doesn't exist at type-check time, hence the suppression below.
// @ts-expect-error — resolved at deploy time by the Cloudflare Pages bundler
import * as build from '../build/server/index.js';

export const onRequest = createPagesFunctionHandler({
  build: build as unknown as ServerBuild,
});
